name: isotope_auth
description: Authentication service base for Isotope apps.
version: 1.0.0
homepage: https://github.com/isotope-studio/isotope_auth

publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
